apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ezra.fullname" . }}
  labels: {{- include "ezra.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: {{- include "ezra.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "ezra.selectorLabels" . | nindent 8 }}
      {{- with .Values.podAnnotations }}
      annotations: {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "ezra.serviceAccountName" . }}
      containers:
        - name: ezra-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
          envFrom:
            - configMapRef:
                name: {{ include "ezra.fullname" . }}-config
            {{- if ne .Values.secrets.backend "gcpSecretManager" }}
            - secretRef:
                name: {{ include "ezra.secretName" . }}
            {{- end }}
          {{- if eq .Values.secrets.backend "gcpSecretManager" }}
          volumeMounts:
            - name: secrets-store
              mountPath: /mnt/secrets-store
              readOnly: true
          {{- end }}
          readinessProbe:
            httpGet:
              path: /ezra/health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /ezra/health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 20
          resources: {{- toYaml .Values.resources | nindent 12 }}
      {{- if eq .Values.secrets.backend "gcpSecretManager" }}
      volumes:
        - name: secrets-store
          csi:
            driver: secrets-store-gke.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: {{ include "ezra.fullname" . }}-secrets
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity: {{- toYaml . | nindent 8 }}
      {{- end }}
