{{- if eq .Values.secrets.backend "gcpSecretManager" }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "ezra.fullname" . }}-secrets
  labels: {{- include "ezra.labels" . | nindent 4 }}
spec:
  provider: gke
  parameters:
    secrets: |
      {{- $project := required "secrets.gcpSecretManager.project is required" .Values.secrets.gcpSecretManager.project }}
      {{- range .Values.secrets.gcpSecretManager.secretIds }}
      - resourceName: "projects/{{ $project }}/secrets/{{ . }}/versions/latest"
        path: "{{ . }}"
      {{- end }}
{{- end }}
